#!/usr/bin/env python3

import re
import string 
import random

# 1.
"""
infile = open("medline.dat", "r")
outfile = open("abstracts.dat", "wb")

for line in infile:
	ID = line
	url = "http://togows.dbcls.jp/entry/ncbi-pubmed/" + ID + "/"
	r = requests.get(url, allow_redirects=True)
	outfile.write(r.content)

outfile.close()


# 2



infile = open("abstracts1.dat", "r")
flag = False
Abstracts = list()
Abs = ""
        

for line in infile:

    End = re.search(r"^[A-Z]+\s+", line)
    if End is not None and Abs != "":
        flag = False
        Abstracts.append(Abs)        
        Abs = ""

    if flag: 
        line = re.sub("\n", " ", line)
        Abs += line 
    
    Reresult = re.search(r"^AB\s+-\s(.+)", line)
    if Reresult is not None:
        flag = True
        Abs += Reresult.group(1).strip()

infile.close()

outfile = open("cleanAbs.dat", "w")
for ABS in Abstracts:
    outfile.write(ABS + "\n")
outfile.close()


print(len(Abstracts))
n = int(len(Abstracts)/10)
tenperc_abs = random.sample(Abstracts, n)


print(len(tenperc_abs))
wcount = dict()
for Abstract in tenperc_abs:
    words = [word.strip(string.punctuation).lower() for word in Abstract.split()]
    for i in words:
        Reresult = re.search(r"([a-z]+(s)?)", i)
        if Reresult is not None and len(Reresult.group(1)) > 2:
            i = Reresult.group(1)
            if i not in wcount:
                wcount[i] = 0
            if i in wcount:
                wcount[i] += 1

print(sum(wcount.values()))
for w in sorted(wcount, key=wcount.get, reverse=True):
    print(w, wcount[w])




outfile = open("blacklist.dat", "w")

for w in wcount:
    n = (wcount[w] / sum(wcount.values())) * 100 
    if n > 0.009: # Modify this limit when we get the actual range with all the abstracts
        outfile.write(w + "\n")
    else:
        pass

outfile.close()


"""
# 3.

infile = open("blacklist.dat", "r")
infile2 = open("shortcleanAbs.dat", "r")
outfile = open("pairs", "w")

blacklist = list()
for line in infile:
    blacklist.append(line[:-1])


relevant_words = dict()
for line in infile2:
    words = [word.strip(string.punctuation).lower() for word in line.split()]
    abstract = list()
    for w in words:
        Reresult = re.search(r"([a-z]+(s)?)", w)
        if Reresult is not None and len(Reresult.group(1)) > 2:   
            if w not in blacklist:
                abstract.append(w)

            else:
                pass
    relevant_words[line] = abstract

# Paring words and counting them
unique_words = dict()
for row in relevant_words:
    w_count = dict()
    for item in relevant_words[row]:

        if item not in w_count:
            w_count[item] = 0
        else:
            w_count[item] += 1

    unique_words[row] = w_count


#Esto es o que hay que averiguar
pairing = dict()
for abst in unique_words:
    words = dict()
    for w in unique_words[abst]:
        cooc = dict()
        d = unique_words[abst]
        name_list = list()
        #print(d)
        for key,value in d.items():
            name_list.append(value)
for v in range(len(name_list)):
    for i in range(v, len(name_list)):
        if name_list[v] <= name_list[i]:
            print(name_list[v])
            
 
        
       
                
        words[w] = cooc

    pairing[abst] = words
        


print(name_list)
